import type { Asteroid } from '@/lib/store';

export type KnownAsteroidCategory = 'popular' | 'trending' | 'hazardous' | 'mission_targets';

export const KNOWN_ASTEROID_CATEGORIES: Record<KnownAsteroidCategory, { label: string; emoji: string; description: string; items: Asteroid[] }> = {
  popular: {
    label: 'Greatest Hits',
    emoji: '🌟',
    description: 'The most famous asteroids ever — start here!',
    items: [
      {
        id: 'chicxulub',
        name: 'Dino Killer (Chicxulub)',
        diameter: 12000,
        velocity: 20.0,
        composition: 'dense_rock',
        date: '66 million years ago',
        source: 'known',
        relativeTime: 'the big one',
        approachType: 'past',
        // The asteroid that wiped out the dinosaurs — hit what is now Mexico
      },
      {
        id: '99942',
        name: 'Apophis — the 2029 close call',
        diameter: 370,
        velocity: 7.42,
        composition: 'dense_rock',
        date: 'Apr 13, 2029',
        dateIso: '2029-04-13T21:46:00.000Z',
        source: 'known',
        isPotentiallyHazardous: true,
        missDistanceKm: 31000,
        missDistance: '31,000 km — closer than TV satellites! You\'ll see it with your eyes.',
        relativeTime: 'in 3 yrs',
        approachType: 'upcoming',
        // 370m rock passing 1/10 the distance to the Moon — inside geostationary orbit
        // Low impact risk this pass, but the flyby could shift its future path
        // A direct hit would mean a ~1 km crater and regional devastation
      },
      {
        id: 'chelyabinsk',
        name: 'Chelyabinsk Fireball',
        diameter: 19,
        velocity: 19.2,
        composition: 'dense_rock',
        date: 'Feb 15, 2013',
        source: 'known',
        relativeTime: 'historical',
        approachType: 'past',
        // Exploded over a Russian city — 1,500 people hurt by broken windows
      },
      {
        id: 'tunguska',
        name: 'Tunguska Explosion',
        diameter: 60,
        velocity: 27.0,
        composition: 'dense_rock',
        date: 'Jun 30, 1908',
        source: 'known',
        relativeTime: 'historical',
        approachType: 'past',
        // Flattened 800 square miles of forest in Siberia — no crater!
      },
      {
        id: '433',
        name: 'Eros (the giant)',
        diameter: 16840,
        velocity: 24.4,
        composition: 'dense_rock',
        date: 'First asteroid orbited by a spacecraft (2000)',
        source: 'known',
        // Shaped like a potato, bigger than a city
      },
      {
        id: '2024pt5',
        name: 'Mini-Moon (2024 PT5)',
        diameter: 10,
        velocity: 0.6,
        composition: 'dense_rock',
        date: 'Sep–Nov 2024',
        source: 'known',
        relativeTime: '2024 capture',
        missDistanceKm: 384400,
        missDistance: '~1 LD — Earth caught it briefly!',
        // Tiny asteroid that orbited Earth for a couple months like a second moon
      },
    ],
  },

  trending: {
    label: 'In The News',
    emoji: '📡',
    description: 'Asteroids scientists are watching right now',
    items: [
      {
        id: '99942b',
        name: 'Apophis (April 2029 flyby)',
        diameter: 370,
        velocity: 7.42,
        composition: 'dense_rock',
        date: 'Apr 13, 2029',
        dateIso: '2029-04-13T21:46:00.000Z',
        source: 'known',
        isPotentiallyHazardous: true,
        missDistanceKm: 31000,
        missDistance: '~31,000 km — inside satellite orbit!',
        relativeTime: 'in 3 yrs',
        approachType: 'upcoming',
      },
      {
        id: '2024yr4',
        name: '2024 YR4',
        diameter: 60,
        velocity: 19.2,
        composition: 'dense_rock',
        date: 'Dec 22, 2032 (potential)',
        dateIso: '2032-12-22T00:00:00.000Z',
        source: 'known',
        isPotentiallyHazardous: true,
        missDistanceKm: 828800,
        missDistance: '2.16 LD',
        relativeTime: 'in 6 yrs',
        approachType: 'upcoming',
      },
      {
        id: '2011wv134',
        name: '(500080) 2011 WV134',
        diameter: 950,
        velocity: 14.1,
        composition: 'dense_rock',
        date: 'Mar 3, 2026',
        dateIso: '2026-03-03T00:00:00.000Z',
        source: 'known',
        isPotentiallyHazardous: true,
        missDistanceKm: 9600000,
        missDistance: '9.6M km (25 LD)',
        relativeTime: 'in weeks',
        approachType: 'upcoming',
      },
      {
        id: '101955',
        name: 'Bennu',
        diameter: 490,
        velocity: 28.0,
        composition: 'porous_rock',
        date: 'OSIRIS-REx brought back a sample (2023)',
        source: 'known',
        isPotentiallyHazardous: true,
        missDistanceKm: 7480000,
        missDistance: '7.5M km',
      },
    ],
  },

  hazardous: {
    label: 'Most Dangerous',
    emoji: '⚠️',
    description: 'Asteroids that could actually be a problem someday',
    items: [
      {
        id: '99942c',
        name: 'Apophis',
        diameter: 370,
        velocity: 7.42,
        composition: 'dense_rock',
        date: 'Apr 13, 2029',
        dateIso: '2029-04-13T21:46:00.000Z',
        missDistanceKm: 31000,
        missDistance: '31,000 km — 1/10 the distance to the Moon',
        source: 'known',
        isPotentiallyHazardous: true,
        relativeTime: 'in 3 yrs',
        approachType: 'upcoming',
      },
      {
        id: '2024yr4b',
        name: '2024 YR4',
        diameter: 60,
        velocity: 19.2,
        composition: 'dense_rock',
        date: 'Dec 22, 2032',
        dateIso: '2032-12-22T00:00:00.000Z',
        source: 'known',
        isPotentiallyHazardous: true,
        missDistanceKm: 828800,
        missDistance: '2.16 LD',
        relativeTime: 'in 6 yrs',
        approachType: 'upcoming',
      },
      { id: '52768', name: '1998 OR2 (the big one)', diameter: 2050, velocity: 8.7, composition: 'dense_rock', date: '2020 close approach', source: 'known', isPotentiallyHazardous: true },
      { id: '2011wv134b', name: '2011 WV134', diameter: 950, velocity: 14.1, composition: 'dense_rock', date: 'Mar 2026', source: 'known', isPotentiallyHazardous: true, relativeTime: 'soon' },
      { id: '410777', name: '2009 FD', diameter: 472, velocity: 15.6, composition: 'dense_rock', date: 'Long-term risk target', source: 'known', isPotentiallyHazardous: true },
      { id: '153814', name: '2001 WN5', diameter: 932, velocity: 10.2, composition: 'dense_rock', date: 'Monitored close approach', source: 'known', isPotentiallyHazardous: true },
    ],
  },

  mission_targets: {
    label: 'Space Missions',
    emoji: '🚀',
    description: 'Asteroids we\'ve actually visited with spacecraft!',
    items: [
      { id: '65803-1', name: 'Dimorphos (we crashed into this one!)', diameter: 151, velocity: 11.8, composition: 'porous_rock', date: 'NASA DART smashed into it to change its orbit', source: 'known' },
      { id: '65803', name: 'Didymos', diameter: 780, velocity: 11.8, composition: 'dense_rock', date: 'DART/Hera deflection test (2022–2024)', source: 'known' },
      { id: '16', name: '16 Psyche (solid metal!)', diameter: 226000, velocity: 16.0, composition: 'iron', date: 'NASA Psyche mission arrives 2026', source: 'known' },
      { id: '101955b', name: 'Bennu (sample returned!)', diameter: 490, velocity: 28.0, composition: 'porous_rock', date: 'OSIRIS-REx brought back a piece (2023)', source: 'known', isPotentiallyHazardous: true },
      { id: 'apophis-apex', name: 'Apophis (OSIRIS-APEX flyby target)', diameter: 370, velocity: 7.42, composition: 'dense_rock', date: 'OSIRIS-APEX will meet it in April 2029', source: 'known', isPotentiallyHazardous: true, missDistanceKm: 31000 },
    ],
  },
};
