import type { Asteroid } from '@/lib/store';

export type KnownAsteroidCategory = 'famous' | 'watch';

// A short, curated set of the asteroids people actually know about.
// Two simple groups: the famous ones from history, and the ones scientists
// are watching now. Plain-English blurbs, no duplicates.
export const KNOWN_ASTEROID_CATEGORIES: Record<
  KnownAsteroidCategory,
  { label: string; emoji: string; items: Asteroid[] }
> = {
  famous: {
    label: 'Famous ones',
    emoji: '🦕',
    items: [
      {
        id: 'chicxulub',
        name: 'The Dinosaur Killer',
        emoji: '🦕',
        blurb: 'The giant that wiped out the dinosaurs 66 million years ago.',
        diameter: 12000,
        velocity: 20.0,
        composition: 'dense_rock',
        date: '66 million years ago',
        source: 'known',
        approachType: 'past',
      },
      {
        id: 'tunguska',
        name: 'The Tunguska Blast',
        emoji: '🌲',
        blurb: 'Exploded over Siberia in 1908 and flattened 800 sq miles of forest — without even hitting the ground.',
        diameter: 60,
        velocity: 27.0,
        composition: 'dense_rock',
        date: '1908',
        source: 'known',
        approachType: 'past',
      },
      {
        id: 'chelyabinsk',
        name: 'The Chelyabinsk Fireball',
        emoji: '🔥',
        blurb: 'Blew up over a Russian city in 2013. The shockwave shattered windows and hurt 1,500 people.',
        diameter: 19,
        velocity: 19.2,
        composition: 'dense_rock',
        date: '2013',
        source: 'known',
        approachType: 'past',
      },
      {
        id: '65803',
        name: 'Dimorphos',
        emoji: '🚀',
        blurb: 'The one NASA crashed a spacecraft into in 2022 to nudge it — our first planetary-defense test.',
        diameter: 151,
        velocity: 6.6,
        composition: 'porous_rock',
        date: 'NASA DART, 2022',
        source: 'known',
        approachType: 'past',
      },
    ],
  },

  watch: {
    label: 'On the watch list',
    emoji: '🔭',
    items: [
      {
        id: '99942',
        name: 'Apophis',
        emoji: '👀',
        blurb: 'In 2029 this 370m rock passes closer than some satellites — you’ll see it with the naked eye. It won’t hit us.',
        diameter: 370,
        velocity: 7.42,
        composition: 'dense_rock',
        date: 'April 13, 2029',
        dateIso: '2029-04-13T21:46:00.000Z',
        source: 'known',
        isPotentiallyHazardous: true,
        missDistanceKm: 31000,
        missDistance: 'Passes ~31,000 km away — closer than TV satellites.',
        relativeTime: '2029',
        approachType: 'upcoming',
      },
      {
        id: '2024yr4',
        name: '2024 YR4',
        emoji: '📡',
        blurb: 'Made headlines as a possible 2032 impactor. Scientists have since ruled out a hit — it’s a near miss.',
        diameter: 60,
        velocity: 19.2,
        composition: 'dense_rock',
        date: 'Watched for 2032',
        dateIso: '2032-12-22T00:00:00.000Z',
        source: 'known',
        isPotentiallyHazardous: true,
        missDistanceKm: 828800,
        missDistance: 'Expected to miss by about twice the Moon’s distance.',
        relativeTime: '2032',
        approachType: 'upcoming',
      },
      {
        id: '101955',
        name: 'Bennu',
        emoji: '🪨',
        blurb: 'NASA flew to it and brought back a sample in 2023. Has a tiny chance of hitting Earth in the 2180s.',
        diameter: 490,
        velocity: 28.0,
        composition: 'porous_rock',
        date: 'Sample returned 2023',
        source: 'known',
        isPotentiallyHazardous: true,
        missDistanceKm: 7480000,
        approachType: 'upcoming',
      },
    ],
  },
};
