import type { Asteroid } from '@/lib/store';

export type KnownAsteroidCategory = 'famous' | 'watch';

// A short, curated set of the asteroids people actually know about.
// Two simple groups: the famous ones from history, and the ones scientists
// are watching now. Plain-English blurbs, no duplicates.
export const KNOWN_ASTEROID_CATEGORIES: Record<
  KnownAsteroidCategory,
  { label: string; emoji: string; items: Asteroid[] }
> = {
  famous: {
    label: 'Famous ones',
    emoji: '🦕',
    items: [
      {
        id: 'chicxulub',
        name: 'The Dinosaur Killer',
        emoji: '🦕',
        blurb: 'The carbonaceous-type giant associated with the dinosaur extinction 66 million years ago.',
        diameter: 12000,
        velocity: 20.0,
        composition: 'porous_rock',
        compositionAssumed: true,
        sourceName: 'LPI / published Chicxulub studies',
        sourceUrl: 'https://www.lpi.usra.edu/science/kring/Chicxulub/',
        inputUncertainty: 'Diameter, speed, and composition are reconstructed from crater studies and are approximate.',
        date: '66 million years ago',
        source: 'known',
        approachType: 'past',
      },
      {
        id: 'tunguska',
        name: 'The Tunguska Blast',
        emoji: '🌲',
        blurb: 'Exploded over Siberia in 1908 and flattened about 830 sq miles of forest — without even hitting the ground.',
        diameter: 60,
        velocity: 27.0,
        composition: 'dense_rock',
        compositionAssumed: true,
        sourceName: 'NASA History',
        sourceUrl: 'https://www.nasa.gov/history/115-years-ago-the-tunguska-asteroid-impact-event/',
        inputUncertainty: 'Object size, velocity, and composition are inferred because no intact impactor was recovered.',
        date: '1908',
        source: 'known',
        approachType: 'past',
      },
      {
        id: 'chelyabinsk',
        name: 'The Chelyabinsk Fireball',
        emoji: '🔥',
        blurb: 'Blew up about 14 miles above Russia in 2013. Broken glass and blast effects injured more than 1,600 people.',
        diameter: 19,
        velocity: 19.2,
        composition: 'dense_rock',
        compositionAssumed: true,
        sourceName: 'NASA Planetary Defense',
        sourceUrl: 'https://www.nasa.gov/solar-system/five-years-after-the-chelyabinsk-meteor-nasa-leads-efforts-in-planetary-defense/',
        inputUncertainty: 'Size and energy are constrained by observations, but local injuries came mostly from building-glass damage.',
        date: '2013',
        source: 'known',
        approachType: 'past',
      },
      {
        id: '65803',
        name: 'Dimorphos',
        emoji: '🚀',
        blurb: 'The one NASA crashed a spacecraft into in 2022 to nudge it — our first planetary-defense test.',
        diameter: 160,
        velocity: 11.2,
        composition: 'porous_rock',
        compositionAssumed: true,
        sourceName: 'NASA DART',
        sourceUrl: 'https://science.nasa.gov/mission/dart/',
        inputUncertainty: 'Dimorphos is not an Earth-impact case; the scenario uses the minimum natural Earth-entry speed, not DART spacecraft impact speed.',
        date: 'NASA DART, 2022',
        source: 'known',
        approachType: 'past',
      },
    ],
  },

  watch: {
    label: 'On the watch list',
    emoji: '🔭',
    items: [
      {
        id: '99942',
        name: 'Apophis',
        emoji: '👀',
        blurb: 'In 2029 this 370m rock safely passes about 32,000 km above Earth — closer than some satellites.',
        diameter: 370,
        velocity: 5.84,
        velocityBasis: 'hyperbolic-excess',
        composition: 'dense_rock',
        compositionAssumed: true,
        sourceName: 'NASA Apophis Facts',
        sourceUrl: 'https://science.nasa.gov/solar-system/asteroids/apophis-facts/',
        inputUncertainty: 'The 2029 event is a safe flyby; modeled impact-entry speed uses JPL v-infinity with Earth-gravity focusing.',
        date: 'April 13, 2029',
        dateIso: '2029-04-13T21:46:00.000Z',
        source: 'known',
        missDistance: 'Passes about 32,000 km above Earth — closer than TV satellites.',
        relativeTime: '2029',
        approachType: 'upcoming',
      },
      {
        id: '2024yr4',
        name: '2024 YR4',
        emoji: '📡',
        blurb: 'Made headlines as a possible 2032 impactor. NASA has ruled out Earth and Moon impacts.',
        diameter: 60,
        velocity: 19.2,
        velocityBasis: 'flyby-relative',
        composition: 'dense_rock',
        compositionAssumed: true,
        sourceName: 'NASA Planetary Defense',
        sourceUrl: 'https://science.nasa.gov/blogs/planetary-defense/2026/03/05/new-nasa-asteroid-observations-eliminate-chance-of-2032-lunar-impact/',
        inputUncertainty: 'NASA has ruled out Earth and lunar impact for 2032; modeled impact-entry speed adds Earth-gravity focusing to the flyby-relative speed.',
        date: '2032 flyby',
        dateIso: '2032-12-22T00:00:00.000Z',
        source: 'known',
        missDistance: 'ESA says it will safely pass the Moon at more than 20,000 km; NASA says it poses no Earth impact risk through the next century.',
        relativeTime: '2032',
        approachType: 'upcoming',
      },
      {
        id: '101955',
        name: 'Bennu',
        emoji: '🪨',
        blurb: 'NASA brought back a sample in 2023. Its highest listed impact risk is 1 in 2,700 on Sept. 24, 2182.',
        diameter: 490,
        velocity: 13.0,
        composition: 'porous_rock',
        densityKgM3: 1260,
        densitySigmaKgM3: 70,
        compositionAssumed: true,
        sourceName: 'NASA OSIRIS-REx',
        sourceUrl: 'https://svs.gsfc.nasa.gov/13896/',
        inputUncertainty: 'Bennu is a rubble-pile asteroid; this uses a published bulk density with uncertainty and a hypothetical Earth-impact speed, not Bennu’s average orbital speed.',
        date: 'Sample returned 2023',
        source: 'known',
        approachType: 'upcoming',
      },
    ],
  },
};
